Update EasySite_env

diff --git a/bin/EasySite_env b/bin/EasySite_env
--- a/bin/EasySite_env
+++ b/bin/EasySite_env
@@ -76,6 +76,26 @@ easysite_file_delete(){
     fi
 }
 
+easysite_file_rename(){
+    if ! easysite_file_check "$1"
+    then
+        echo -e "${BOLD}> ${LRED}The file ${LYELLOW}$1 ${LRED}doesn't exists.${RESET}"
+        return 1
+    elif easysite_file_check "$2" || easysite_dir_check "$2"
+    then
+        echo -e "${BOLD}> ${LRED}A file or directory named ${LYELLOW}$2 ${LRED}already exists.${RESET}"
+        return 1
+    else
+        if output=$(mv "$1" "$2" 2>&1)
+        then
+            return 0
+        else
+            echo -e "${RED}Failed to rename file ${LYELLOW}$1 ${RED}: ${LRED}$output${RESET}"
+            return 1
+        fi
+    fi
+}
+
 easysite_dir_check(){
     if [ -d "$1" ]
     then
@@ -112,6 +132,26 @@ easysite_dir_delete(){
             return 0
         else
             echo -e "${RED}Failed to delete directory ${LYELLOW}$1 ${RED}: ${LRED}$output${RESET}"
+            return 1
+        fi
+    fi
+}
+
+easysite_dir_rename(){
+    if ! easysite_dir_check "$1"
+    then
+        echo -e "${BOLD}> ${LRED}The directory ${LYELLOW}$1 ${LRED}doesn't exists.${RESET}"
+        return 1
+    elif easysite_dir_check "$2" || easysite_file_check "$2"
+    then
+        echo -e "${BOLD}> ${LRED}A file or directory named ${LYELLOW}$2 ${LRED}already exists.${RESET}"
+        return 1
+    else
+        if output=$(mv "$1" "$2" 2>&1)
+        then
+            return 0
+        else
+            echo -e "${RED}Failed to rename directory ${LYELLOW}$1 ${RED}: ${LRED}$output${RESET}"
             return 1
         fi
     fi
